spring:
  application:
     name: convert-uat
  cloud:
    loadbalancer:
      ribbon:
        #enabled: true




server:
  port: 8086
  #ssl:
   # key-alias: selfsigned_localhost_sslserver
   # key-password: changeit
   # key-store: D:\ProjectB\ConversionDemo\src\main\resources\ssl-server.jks
   # key-store-provider: SUN
    #key-store-type: JKS

management.endpoints.web.exposure.include: "*"

zebpayapp: http://localhost:8084/zebpay/ticker/
bitkub: https://localhost:8082/bitkub/ticker/

eureka:
  vipAddress: http://localhost:8761
  port:
      enabled: true
  traffic:
    enabled: true
  serviceUrl:
    default: http://localhost:8761/eureka/
  client:
    registerWithEureka: true
    fetchRegistry: true
    instance:
      #preferIpAddress: true
  preferSameZone: true
